version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build web docker image and push image to docker hub
          command: |
            set -e
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./pipe_build_up_test.sh
            docker tag cyberdojo/web:latest cyberdojo/web:${CIRCLE_SHA1:0:7}
            docker tag cyberdojo/web:latest cyberdojo/web:beta
            docker push cyberdojo/web:${CIRCLE_SHA1:0:7}
            docker push cyberdojo/web:beta

  deploy-image-to-beta:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - run:
          name: authenticate with gcloud and deploy with helm
          command: |
            set -e
            echo $GCP_K8S_CREDENTIALS > /gcp/gcp-credentials.json
            gcloud auth activate-service-account "$SERVICE_ACCOUNT" --key-file=/gcp/gcp-credentials.json
            gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE" --project "$PROJECT"
            helm init --client-only
            helm repo add praqma https://praqma-helm-repo.s3.amazonaws.com/
            #helm upgrade --install --reuse-values --namespace=beta --set-string image.web.tag=${CIRCLE_SHA1:0:7} beta-cyber-dojo praqma/cyber-dojo
            helm upgrade --install --namespace=beta --set-string image.web.tag=${CIRCLE_SHA1:0:7} beta-cyber-dojo praqma/cyber-dojo

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
      - deploy-image-to-beta:
          context: cyberdojo-context
          requires:
            - build-image
