
nginx:
  image: cyberdojo/nginx
  container_name: cyber-dojo-nginx
  cpu_shares: 256
  restart: on-failure
  mem_limit: 50M
  memswap_limit: 50M
  links:
    - "web:cyberdojo_web"
  ports:
    - 80:80

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# I'd like to set cpu/memory/swap limits on the test-run containers
# and the web server container independently.
# This appears to be impossible so I have to try to get some kind
# of compromise; I don't want to limit the web-server but I do want
# to limit the test-containers. However if the limits are too low
# the web server container is unable to [docker pull] images on-demand
# in the setup pages.

web:
  user: cyber-dojo
  image: ${CYBER_DOJO_WEB_SERVER}
  container_name: ${CYBER_DOJO_WEB_CONTAINER}
  cpu_shares: 512
  restart: on-failure
  mem_limit: 2G
  memswap_limit: 2G
  command: rails server --environment=${CYBER_DOJO_RAILS_ENVIRONMENT}
  links:
    - differ
  environment:
    - CYBER_DOJO_SHELL_CLASS
    - CYBER_DOJO_DISK_CLASS
    - CYBER_DOJO_LOG_CLASS
    - CYBER_DOJO_GIT_CLASS
    - CYBER_DOJO_STORER_CLASS
    - CYBER_DOJO_RUNNER_CLASS
    - CYBER_DOJO_RUNNER_SUDO
    - CYBER_DOJO_RUNNER_TIMEOUT
    - CYBER_DOJO_LANGUAGES_ROOT=${CYBER_DOJO_ROOT}/start_points/languages
    - CYBER_DOJO_EXERCISES_ROOT=${CYBER_DOJO_ROOT}/start_points/exercises
    - CYBER_DOJO_CUSTOM_ROOT=${CYBER_DOJO_ROOT}/start_points/custom
    - CYBER_DOJO_KATAS_ROOT=${CYBER_DOJO_ROOT}/katas
  ports:
    - 3000:3000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${CYBER_DOJO_START_POINT_LANGUAGES}:${CYBER_DOJO_ROOT}/start_points/languages:ro
    - ${CYBER_DOJO_START_POINT_EXERCISES}:${CYBER_DOJO_ROOT}/start_points/exercises:ro
    - ${CYBER_DOJO_START_POINT_CUSTOM}:${CYBER_DOJO_ROOT}/start_points/custom:ro
  volumes_from:
    - ${CYBER_DOJO_KATAS_DATA_CONTAINER}:rw


differ:
  user: nobody
  image: cyberdojo/differ
  container_name: cyber-dojo-differ
  cpu_shares: 256
  restart: on-failure
  entrypoint:
    - foreman
    - start
    - -d
    - /app
  ports:
    - 4567:4567

