
nginx:
  image: cyberdojo/nginx
  container_name: cyber-dojo-nginx
  restart: always
  links:
    - "web:cyberdojo_web"
  ports:
    - "80:80"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  user: cyber-dojo
  image: ${CYBER_DOJO_WEB_SERVER}
  container_name: ${CYBER_DOJO_WEB_CONTAINER}
  restart: always
  command: rails server --environment=${CYBER_DOJO_RAILS_ENVIRONMENT}
  environment:
    - CYBER_DOJO_SHELL_CLASS
    - CYBER_DOJO_DISK_CLASS
    - CYBER_DOJO_LOG_CLASS
    - CYBER_DOJO_GIT_CLASS
    - CYBER_DOJO_KATAS_CLASS
    - CYBER_DOJO_RUNNER_CLASS
    - CYBER_DOJO_RUNNER_SUDO
    - CYBER_DOJO_RUNNER_TIMEOUT
    - CYBER_DOJO_LANGUAGES_ROOT=${CYBER_DOJO_DATA_ROOT}/languages
    - CYBER_DOJO_EXERCISES_ROOT=${CYBER_DOJO_DATA_ROOT}/exercises
    - CYBER_DOJO_CUSTOM_ROOT=${CYBER_DOJO_DATA_ROOT}/custom
    - CYBER_DOJO_KATAS_ROOT=${CYBER_DOJO_KATAS_ROOT}
  ports:
    - "3000:3000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${CYBER_DOJO_LANGUAGES_VOLUME}:${CYBER_DOJO_DATA_ROOT}/languages:ro
    - ${CYBER_DOJO_EXERCISES_VOLUME}:${CYBER_DOJO_DATA_ROOT}/exercises:ro
    - ${CYBER_DOJO_CUSTOM_VOLUME}:${CYBER_DOJO_DATA_ROOT}/custom:ro
  volumes_from:
    - ${CYBER_DOJO_KATAS_DATA_CONTAINER}:rw

