# the image names comprising the server are
#   cyberdojofoundation/nginx:latest
#   cyberdojofoundation/web:${DOCKER_VERSION}
# if these change then the upgrade command in
# cyber-dojo.rb will also need changing.

nginx:
  image: cyberdojofoundation/nginx
  container_name: cdf-nginx
  links:
    - "web:cyberdojo_web"
  ports:
    - "80:80"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  user: cyber-dojo
  image: cyberdojofoundation/web:${DOCKER_VERSION}
  container_name: cdf-web
  command: rails server --environment=development
  environment:
    - CYBER_DOJO_SHELL_CLASS
    - CYBER_DOJO_DISK_CLASS
    - CYBER_DOJO_LOG_CLASS
    - CYBER_DOJO_GIT_CLASS
    - CYBER_DOJO_KATAS_CLASS
    - CYBER_DOJO_RUNNER_CLASS
    - CYBER_DOJO_RUNNER_SUDO
    - CYBER_DOJO_RUNNER_TIMEOUT
    - CYBER_DOJO_LANGUAGES_ROOT=${CYBER_DOJO_HOME}/app/data/languages
    - CYBER_DOJO_EXERCISES_ROOT=${CYBER_DOJO_HOME}/app/data/exercises
    - CYBER_DOJO_CUSTOM_ROOT=${CYBER_DOJO_HOME}/app/data/custom
    - CYBER_DOJO_KATAS_ROOT=${CYBER_DOJO_HOME}/app/data/katas
  ports:
    - "3000:3000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${CYBER_DOJO_DATA_ROOT}/languages:${CYBER_DOJO_HOME}/app/data/languages:ro
    - ${CYBER_DOJO_DATA_ROOT}/exercises:${CYBER_DOJO_HOME}/app/data/exercises:ro
    - ${CYBER_DOJO_DATA_ROOT}/custom:${CYBER_DOJO_HOME}/app/data/custom:rw
    - ${CYBER_DOJO_KATAS_ROOT}:${CYBER_DOJO_HOME}/app/data/katas:rw
